name: Build and Deploy Dev Images

on:
  push:
    branches: [ "develop" ]

jobs:
  build_core:
    name: Build & Push Core Superset Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core Code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Docker Buildx (Core)
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR (Core)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build & Push Core Image
        run: |
          docker build --no-cache -t ${{ secrets.ACR_LOGIN_SERVER }}/re-superset:develop-latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/re-superset:develop-latest

  deploy:
    name: Deploy to Dev Server    
    needs: [build_core]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_KEY }}
          known_hosts: ${{ secrets.DEV_SSH_HOST }}

      - name: Deploy to Dev Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} "
            echo \"${{ secrets.ACR_PASSWORD }}\" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u \"${{ secrets.ACR_USERNAME }}\" --password-stdin &&
            docker pull ${{ secrets.ACR_LOGIN_SERVER }}/re-superset:develop-latest &&
            cd /home/supersetuser/re-superset && \
            docker compose up -d
          "

